package megasena.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.JTextField;

/**
 *
 * @author Luiz Flávio
 */
public class MegaSenaView extends javax.swing.JFrame {

    /**
     * Creates new form MegaSenaView
     */
    public MegaSenaView() {
        setIcon();
        initComponents();
        centralizarTela();
        setResizable(false);
        setTitle("Loterias Caixa - Mega-Sena");
        barraDeProgresso.setStringPainted(true);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGerarApostas = new javax.swing.JLabel();
        btnAjudaGerarApostas = new javax.swing.JButton();
        separadorVertical = new javax.swing.JSeparator();
        lblQtdeApostas = new javax.swing.JLabel();
        txtQtdeApostas = new javax.swing.JTextField();
        lblNumConcursoGerarApostas = new javax.swing.JLabel();
        txtNumConcursoGerarApostas = new javax.swing.JTextField();
        lblNumThreads = new javax.swing.JLabel();
        txtNumThreads = new javax.swing.JTextField();
        btnGerarApostas = new javax.swing.JButton();
        separadorHorizontal1 = new javax.swing.JSeparator();
        lblValidarApostas = new javax.swing.JLabel();
        btnAjudaValidarApostas = new javax.swing.JButton();
        lblNumSorteio = new javax.swing.JLabel();
        txtNum1Sorteio = new javax.swing.JTextField();
        txtNum2Sorteio = new javax.swing.JTextField();
        txtNum3Sorteio = new javax.swing.JTextField();
        txtNum4Sorteio = new javax.swing.JTextField();
        txtNum5Sorteio = new javax.swing.JTextField();
        txtNum6Sorteio = new javax.swing.JTextField();
        lblNumConcursoValidarApostas = new javax.swing.JLabel();
        txtNumConcursoValidarApostas = new javax.swing.JTextField();
        btnValidarApostas = new javax.swing.JButton();
        separadorHorizontal2 = new javax.swing.JSeparator();
        lblQtdeApostasVencedoras = new javax.swing.JLabel();
        lbl6Numeros = new javax.swing.JLabel();
        txt6Numeros = new javax.swing.JTextField();
        lbl4Numeros = new javax.swing.JLabel();
        txt4Numeros = new javax.swing.JTextField();
        lbl5Numeros = new javax.swing.JLabel();
        txt5Numeros = new javax.swing.JTextField();
        separadorHorizontal3 = new javax.swing.JSeparator();
        barraDeProgresso = new javax.swing.JProgressBar();
        lblCombinacoesPossiveis = new javax.swing.JLabel();
        lbl6NumerosCombinacoesPossiveis = new javax.swing.JLabel();
        txtNum1CombinacoesPossiveis = new javax.swing.JTextField();
        txtNum2CombinacoesPossiveis = new javax.swing.JTextField();
        txtNum3CombinacoesPossiveis = new javax.swing.JTextField();
        txtNum4CombinacoesPossiveis = new javax.swing.JTextField();
        txtNum5CombinacoesPossiveis = new javax.swing.JTextField();
        txtNum6CombinacoesPossiveis = new javax.swing.JTextField();
        btnAjudaCombinacoesPossiveis = new javax.swing.JButton();
        lbl5NumerosCombinacoesPossiveis = new javax.swing.JLabel();
        txt5Numeros1CombinacoesPossiveis = new javax.swing.JTextField();
        txt5Numeros2CombinacoesPossiveis = new javax.swing.JTextField();
        txt5Numeros3CombinacoesPossiveis = new javax.swing.JTextField();
        txt5Numeros4CombinacoesPossiveis = new javax.swing.JTextField();
        txt5Numeros5CombinacoesPossiveis = new javax.swing.JTextField();
        txt5Numeros6CombinacoesPossiveis = new javax.swing.JTextField();
        lbl4NumerosCombinacoesPossiveis = new javax.swing.JLabel();
        txt4Numeros1CombinacoesPossiveis = new javax.swing.JTextField();
        txt4Numeros2CombinacoesPossiveis = new javax.swing.JTextField();
        txt4Numeros3CombinacoesPossiveis = new javax.swing.JTextField();
        txt4Numeros4CombinacoesPossiveis = new javax.swing.JTextField();
        txt4Numeros5CombinacoesPossiveis = new javax.swing.JTextField();
        txt4Numeros6CombinacoesPossiveis = new javax.swing.JTextField();
        txt4Numeros9CombinacoesPossiveis = new javax.swing.JTextField();
        txt4Numeros7CombinacoesPossiveis = new javax.swing.JTextField();
        txt4Numeros8CombinacoesPossiveis = new javax.swing.JTextField();
        txt4Numeros10CombinacoesPossiveis = new javax.swing.JTextField();
        txt4Numeros12CombinacoesPossiveis = new javax.swing.JTextField();
        txt4Numeros11CombinacoesPossiveis = new javax.swing.JTextField();
        txt4Numeros13CombinacoesPossiveis = new javax.swing.JTextField();
        txt4Numeros15CombinacoesPossiveis = new javax.swing.JTextField();
        txt4Numeros14CombinacoesPossiveis = new javax.swing.JTextField();
        btnGerarCombinacoesPossiveis = new javax.swing.JButton();
        lblNomeDesenvolvedor = new javax.swing.JLabel();
        lblTempoExecução = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblGerarApostas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGerarApostas.setText("Gerar Apostas:");

        btnAjudaGerarApostas.setText("Ajuda");

        separadorVertical.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblQtdeApostas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblQtdeApostas.setText("Qtde de Apostas:");
        lblQtdeApostas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtQtdeApostas.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblNumConcursoGerarApostas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumConcursoGerarApostas.setText("Concurso:");
        lblNumConcursoGerarApostas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblNumConcursoGerarApostas.setMaximumSize(new java.awt.Dimension(85, 14));
        lblNumConcursoGerarApostas.setMinimumSize(new java.awt.Dimension(85, 14));
        lblNumConcursoGerarApostas.setPreferredSize(new java.awt.Dimension(85, 14));

        txtNumConcursoGerarApostas.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblNumThreads.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumThreads.setText("Nº de Threads:");
        lblNumThreads.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblNumThreads.setMaximumSize(new java.awt.Dimension(85, 14));
        lblNumThreads.setMinimumSize(new java.awt.Dimension(85, 14));
        lblNumThreads.setPreferredSize(new java.awt.Dimension(85, 14));

        txtNumThreads.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnGerarApostas.setText("Gerar Apostas");

        lblValidarApostas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblValidarApostas.setText("Validar Apostas:");

        btnAjudaValidarApostas.setText("Ajuda");

        lblNumSorteio.setText("Nº s do Sorteio");

        txtNum1Sorteio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNum2Sorteio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNum3Sorteio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNum4Sorteio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNum5Sorteio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNum6Sorteio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblNumConcursoValidarApostas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumConcursoValidarApostas.setText("Concurso:");
        lblNumConcursoValidarApostas.setMaximumSize(new java.awt.Dimension(85, 14));
        lblNumConcursoValidarApostas.setMinimumSize(new java.awt.Dimension(85, 14));
        lblNumConcursoValidarApostas.setPreferredSize(new java.awt.Dimension(85, 14));

        txtNumConcursoValidarApostas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumConcursoValidarApostas.setPreferredSize(new java.awt.Dimension(75, 20));

        btnValidarApostas.setText("Validar Números");
        btnValidarApostas.setMaximumSize(new java.awt.Dimension(101, 23));
        btnValidarApostas.setMinimumSize(new java.awt.Dimension(101, 23));
        btnValidarApostas.setPreferredSize(new java.awt.Dimension(101, 23));

        lblQtdeApostasVencedoras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQtdeApostasVencedoras.setText("Quantidade de Apostas Vencedoreas:");

        lbl6Numeros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl6Numeros.setText("6 Números:");
        lbl6Numeros.setMaximumSize(new java.awt.Dimension(85, 14));
        lbl6Numeros.setMinimumSize(new java.awt.Dimension(85, 14));
        lbl6Numeros.setPreferredSize(new java.awt.Dimension(85, 14));

        txt6Numeros.setEditable(false);
        txt6Numeros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt6Numeros.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt6Numeros.setBorder(null);
        txt6Numeros.setPreferredSize(new java.awt.Dimension(75, 20));
        txt6Numeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt6NumerosActionPerformed(evt);
            }
        });

        lbl4Numeros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl4Numeros.setText("4 Números:");
        lbl4Numeros.setMaximumSize(new java.awt.Dimension(85, 14));
        lbl4Numeros.setMinimumSize(new java.awt.Dimension(85, 14));
        lbl4Numeros.setPreferredSize(new java.awt.Dimension(85, 14));

        txt4Numeros.setEditable(false);
        txt4Numeros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt4Numeros.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt4Numeros.setBorder(null);
        txt4Numeros.setPreferredSize(new java.awt.Dimension(75, 20));

        lbl5Numeros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl5Numeros.setText("5 Números:");
        lbl5Numeros.setMaximumSize(new java.awt.Dimension(85, 14));
        lbl5Numeros.setMinimumSize(new java.awt.Dimension(85, 14));
        lbl5Numeros.setPreferredSize(new java.awt.Dimension(85, 14));

        txt5Numeros.setEditable(false);
        txt5Numeros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt5Numeros.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt5Numeros.setBorder(null);
        txt5Numeros.setPreferredSize(new java.awt.Dimension(75, 20));

        lblCombinacoesPossiveis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCombinacoesPossiveis.setText("Combinações Possíveis:");

        lbl6NumerosCombinacoesPossiveis.setText("6 Números:");

        txtNum1CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNum2CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNum3CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNum4CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNum5CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNum6CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnAjudaCombinacoesPossiveis.setText("Ajuda");

        lbl5NumerosCombinacoesPossiveis.setText("5 Números:");

        txt5Numeros1CombinacoesPossiveis.setEditable(false);
        txt5Numeros1CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt5Numeros2CombinacoesPossiveis.setEditable(false);
        txt5Numeros2CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt5Numeros3CombinacoesPossiveis.setEditable(false);
        txt5Numeros3CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt5Numeros4CombinacoesPossiveis.setEditable(false);
        txt5Numeros4CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt5Numeros5CombinacoesPossiveis.setEditable(false);
        txt5Numeros5CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt5Numeros6CombinacoesPossiveis.setEditable(false);
        txt5Numeros6CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbl4NumerosCombinacoesPossiveis.setText("4 Números:");

        txt4Numeros1CombinacoesPossiveis.setEditable(false);
        txt4Numeros1CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt4Numeros2CombinacoesPossiveis.setEditable(false);
        txt4Numeros2CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt4Numeros3CombinacoesPossiveis.setEditable(false);
        txt4Numeros3CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt4Numeros4CombinacoesPossiveis.setEditable(false);
        txt4Numeros4CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt4Numeros5CombinacoesPossiveis.setEditable(false);
        txt4Numeros5CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt4Numeros6CombinacoesPossiveis.setEditable(false);
        txt4Numeros6CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt4Numeros9CombinacoesPossiveis.setEditable(false);
        txt4Numeros9CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt4Numeros7CombinacoesPossiveis.setEditable(false);
        txt4Numeros7CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt4Numeros8CombinacoesPossiveis.setEditable(false);
        txt4Numeros8CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt4Numeros10CombinacoesPossiveis.setEditable(false);
        txt4Numeros10CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt4Numeros12CombinacoesPossiveis.setEditable(false);
        txt4Numeros12CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt4Numeros11CombinacoesPossiveis.setEditable(false);
        txt4Numeros11CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt4Numeros13CombinacoesPossiveis.setEditable(false);
        txt4Numeros13CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt4Numeros15CombinacoesPossiveis.setEditable(false);
        txt4Numeros15CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt4Numeros14CombinacoesPossiveis.setEditable(false);
        txt4Numeros14CombinacoesPossiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnGerarCombinacoesPossiveis.setText("Gerar Combinações");

        lblNomeDesenvolvedor.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblNomeDesenvolvedor.setForeground(new java.awt.Color(51, 51, 51));
        lblNomeDesenvolvedor.setText("Luiz Flávio Pereira");

        lblTempoExecução.setText("Tempo de execução: 0 s.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValidarApostas)
                        .addGap(148, 148, 148)
                        .addComponent(btnAjudaValidarApostas))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblNumThreads, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQtdeApostas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNumThreads, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGerarApostas, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAjudaGerarApostas)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblGerarApostas)
                                    .addGap(143, 143, 143))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblQtdeApostas)
                                    .addGap(62, 62, 62)
                                    .addComponent(lblNumConcursoGerarApostas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addComponent(txtNumConcursoGerarApostas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblNumSorteio, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtNum1Sorteio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNum2Sorteio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNum3Sorteio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNum4Sorteio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNum5Sorteio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNum6Sorteio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblQtdeApostasVencedoras, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbl6Numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt6Numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbl5Numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt5Numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbl4Numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt4Numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(separadorHorizontal1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNumConcursoValidarApostas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumConcursoValidarApostas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnValidarApostas, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(separadorHorizontal2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separadorHorizontal3)
                    .addComponent(barraDeProgresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(separadorVertical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl6NumerosCombinacoesPossiveis)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNum1CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNum2CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNum3CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNum4CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNum5CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNum6CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGerarCombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCombinacoesPossiveis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAjudaCombinacoesPossiveis))
                    .addComponent(lbl5NumerosCombinacoesPossiveis)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt5Numeros1CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt5Numeros2CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt5Numeros3CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt5Numeros4CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt5Numeros5CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt5Numeros6CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl4NumerosCombinacoesPossiveis)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt4Numeros1CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt4Numeros2CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt4Numeros3CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt4Numeros4CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt4Numeros5CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt4Numeros6CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt4Numeros7CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt4Numeros8CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt4Numeros9CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt4Numeros10CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt4Numeros11CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt4Numeros12CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt4Numeros13CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt4Numeros14CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt4Numeros15CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTempoExecução, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNomeDesenvolvedor)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGerarApostas)
                            .addComponent(btnAjudaGerarApostas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQtdeApostas)
                            .addComponent(txtQtdeApostas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumConcursoGerarApostas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumConcursoGerarApostas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumThreads, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumThreads, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGerarApostas))
                        .addGap(7, 7, 7)
                        .addComponent(separadorHorizontal1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValidarApostas)
                            .addComponent(btnAjudaValidarApostas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumSorteio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNum1Sorteio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNum2Sorteio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNum3Sorteio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNum4Sorteio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNum5Sorteio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNum6Sorteio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumConcursoValidarApostas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumConcursoValidarApostas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnValidarApostas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(separadorHorizontal2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQtdeApostasVencedoras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl6Numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt6Numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl5Numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt5Numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl4Numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt4Numeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separadorHorizontal3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barraDeProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCombinacoesPossiveis)
                                    .addComponent(btnAjudaCombinacoesPossiveis))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl6NumerosCombinacoesPossiveis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNum1CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNum2CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNum3CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNum4CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNum5CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNum6CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGerarCombinacoesPossiveis))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl5NumerosCombinacoesPossiveis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt5Numeros1CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt5Numeros2CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt5Numeros3CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt5Numeros4CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt5Numeros5CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt5Numeros6CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl4NumerosCombinacoesPossiveis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt4Numeros1CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt4Numeros2CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt4Numeros3CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt4Numeros4CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt4Numeros5CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt4Numeros6CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt4Numeros7CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt4Numeros8CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt4Numeros9CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt4Numeros10CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt4Numeros11CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt4Numeros12CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt4Numeros13CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt4Numeros14CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt4Numeros15CombinacoesPossiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNomeDesenvolvedor, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTempoExecução, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(separadorVertical))
                        .addContainerGap())))
        );

        txtQtdeApostas.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt6NumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt6NumerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt6NumerosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null, "Error at MegaSenaView.java(line 610):\n\n".concat(ex.getMessage()), "Falha", JOptionPane.ERROR_MESSAGE);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MegaSenaView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraDeProgresso;
    private javax.swing.JButton btnAjudaCombinacoesPossiveis;
    private javax.swing.JButton btnAjudaGerarApostas;
    private javax.swing.JButton btnAjudaValidarApostas;
    private javax.swing.JButton btnGerarApostas;
    private javax.swing.JButton btnGerarCombinacoesPossiveis;
    private javax.swing.JButton btnValidarApostas;
    private javax.swing.JLabel lbl4Numeros;
    private javax.swing.JLabel lbl4NumerosCombinacoesPossiveis;
    private javax.swing.JLabel lbl5Numeros;
    private javax.swing.JLabel lbl5NumerosCombinacoesPossiveis;
    private javax.swing.JLabel lbl6Numeros;
    private javax.swing.JLabel lbl6NumerosCombinacoesPossiveis;
    private javax.swing.JLabel lblCombinacoesPossiveis;
    private javax.swing.JLabel lblGerarApostas;
    private javax.swing.JLabel lblNomeDesenvolvedor;
    private javax.swing.JLabel lblNumConcursoGerarApostas;
    private javax.swing.JLabel lblNumConcursoValidarApostas;
    private javax.swing.JLabel lblNumSorteio;
    private javax.swing.JLabel lblNumThreads;
    private javax.swing.JLabel lblQtdeApostas;
    private javax.swing.JLabel lblQtdeApostasVencedoras;
    private javax.swing.JLabel lblTempoExecução;
    private javax.swing.JLabel lblValidarApostas;
    private javax.swing.JSeparator separadorHorizontal1;
    private javax.swing.JSeparator separadorHorizontal2;
    private javax.swing.JSeparator separadorHorizontal3;
    private javax.swing.JSeparator separadorVertical;
    private javax.swing.JTextField txt4Numeros;
    private javax.swing.JTextField txt4Numeros10CombinacoesPossiveis;
    private javax.swing.JTextField txt4Numeros11CombinacoesPossiveis;
    private javax.swing.JTextField txt4Numeros12CombinacoesPossiveis;
    private javax.swing.JTextField txt4Numeros13CombinacoesPossiveis;
    private javax.swing.JTextField txt4Numeros14CombinacoesPossiveis;
    private javax.swing.JTextField txt4Numeros15CombinacoesPossiveis;
    private javax.swing.JTextField txt4Numeros1CombinacoesPossiveis;
    private javax.swing.JTextField txt4Numeros2CombinacoesPossiveis;
    private javax.swing.JTextField txt4Numeros3CombinacoesPossiveis;
    private javax.swing.JTextField txt4Numeros4CombinacoesPossiveis;
    private javax.swing.JTextField txt4Numeros5CombinacoesPossiveis;
    private javax.swing.JTextField txt4Numeros6CombinacoesPossiveis;
    private javax.swing.JTextField txt4Numeros7CombinacoesPossiveis;
    private javax.swing.JTextField txt4Numeros8CombinacoesPossiveis;
    private javax.swing.JTextField txt4Numeros9CombinacoesPossiveis;
    private javax.swing.JTextField txt5Numeros;
    private javax.swing.JTextField txt5Numeros1CombinacoesPossiveis;
    private javax.swing.JTextField txt5Numeros2CombinacoesPossiveis;
    private javax.swing.JTextField txt5Numeros3CombinacoesPossiveis;
    private javax.swing.JTextField txt5Numeros4CombinacoesPossiveis;
    private javax.swing.JTextField txt5Numeros5CombinacoesPossiveis;
    private javax.swing.JTextField txt5Numeros6CombinacoesPossiveis;
    private javax.swing.JTextField txt6Numeros;
    private javax.swing.JTextField txtNum1CombinacoesPossiveis;
    private javax.swing.JTextField txtNum1Sorteio;
    private javax.swing.JTextField txtNum2CombinacoesPossiveis;
    private javax.swing.JTextField txtNum2Sorteio;
    private javax.swing.JTextField txtNum3CombinacoesPossiveis;
    private javax.swing.JTextField txtNum3Sorteio;
    private javax.swing.JTextField txtNum4CombinacoesPossiveis;
    private javax.swing.JTextField txtNum4Sorteio;
    private javax.swing.JTextField txtNum5CombinacoesPossiveis;
    private javax.swing.JTextField txtNum5Sorteio;
    private javax.swing.JTextField txtNum6CombinacoesPossiveis;
    private javax.swing.JTextField txtNum6Sorteio;
    private javax.swing.JTextField txtNumConcursoGerarApostas;
    private javax.swing.JTextField txtNumConcursoValidarApostas;
    private javax.swing.JTextField txtNumThreads;
    private javax.swing.JTextField txtQtdeApostas;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAjudaGerarApostas() {
        return btnAjudaGerarApostas;
    }

    public void setBtnAjudaGerarApostas(JButton btnAjudaGerarApostas) {
        this.btnAjudaGerarApostas = btnAjudaGerarApostas;
    }

    public JButton getBtnAjudaValidarApostas() {
        return btnAjudaValidarApostas;
    }

    public void setBtnAjudaValidarApostas(JButton btnAjudaValidarApostas) {
        this.btnAjudaValidarApostas = btnAjudaValidarApostas;
    }

    public JButton getBtnGerarApostas() {
        return btnGerarApostas;
    }

    public void setBtnGerarApostas(JButton btnGerarApostas) {
        this.btnGerarApostas = btnGerarApostas;
    }

    public JButton getBtnValidarApostas() {
        return btnValidarApostas;
    }

    public void setBtnValidarApostas(JButton btnValidarApostas) {
        this.btnValidarApostas = btnValidarApostas;
    }

    public JTextField getTxt4Numeros() {
        return txt4Numeros;
    }

    public void setTxt4Numeros(JTextField txt4Numeros) {
        this.txt4Numeros = txt4Numeros;
    }

    public JTextField getTxt5Numeros() {
        return txt5Numeros;
    }

    public void setTxt5Numeros(JTextField txt5Numeros) {
        this.txt5Numeros = txt5Numeros;
    }

    public JTextField getTxt6Numeros() {
        return txt6Numeros;
    }

    public void setTxt6Numeros(JTextField txt6Numeros) {
        this.txt6Numeros = txt6Numeros;
    }

    public JTextField getTxtNum1Sorteio() {
        return txtNum1Sorteio;
    }

    public void setTxtNum1Sorteio(JTextField txtNum1Sorteio) {
        this.txtNum1Sorteio = txtNum1Sorteio;
    }

    public JTextField getTxtNum2Sorteio() {
        return txtNum2Sorteio;
    }

    public void setTxtNum2Sorteio(JTextField txtNum2Sorteio) {
        this.txtNum2Sorteio = txtNum2Sorteio;
    }

    public JTextField getTxtNum3Sorteio() {
        return txtNum3Sorteio;
    }

    public void setTxtNum3Sorteio(JTextField txtNum3Sorteio) {
        this.txtNum3Sorteio = txtNum3Sorteio;
    }

    public JTextField getTxtNum4Sorteio() {
        return txtNum4Sorteio;
    }

    public void setTxtNum4Sorteio(JTextField txtNum4Sorteio) {
        this.txtNum4Sorteio = txtNum4Sorteio;
    }

    public JTextField getTxtNum5Sorteio() {
        return txtNum5Sorteio;
    }

    public void setTxtNum5Sorteio(JTextField txtNum5Sorteio) {
        this.txtNum5Sorteio = txtNum5Sorteio;
    }

    public JTextField getTxtNum6Sorteio() {
        return txtNum6Sorteio;
    }

    public void setTxtNum6Sorteio(JTextField txtNum6Sorteio) {
        this.txtNum6Sorteio = txtNum6Sorteio;
    }

    public JTextField getTxtNumConcursoGerarApostas() {
        return txtNumConcursoGerarApostas;
    }

    public void setTxtNumConcursoGerarApostas(JTextField txtNumConcursoGerarApostas) {
        this.txtNumConcursoGerarApostas = txtNumConcursoGerarApostas;
    }

    public JTextField getTxtNumConcursoValidarApostas() {
        return txtNumConcursoValidarApostas;
    }

    public void setTxtNumConcursoValidarApostas(JTextField txtNumConcursoValidarApostas) {
        this.txtNumConcursoValidarApostas = txtNumConcursoValidarApostas;
    }

    public JTextField getTxtNumThreads() {
        return txtNumThreads;
    }

    public void setTxtNumThreads(JTextField txtNumThreads) {
        this.txtNumThreads = txtNumThreads;
    }

    public JTextField getTxtQtdeApostas() {
        return txtQtdeApostas;
    }

    public void setTxtQtdeApostas(JTextField txtQtdeApostas) {
        this.txtQtdeApostas = txtQtdeApostas;
    }

    public JProgressBar getBarraDeProgresso() {
        return barraDeProgresso;
    }

    public void setBarraDeProgresso(JProgressBar barraDeProgresso) {
        this.barraDeProgresso = barraDeProgresso;
    }

    public JButton getBtnAjudaCombinacoesPossiveis() {
        return btnAjudaCombinacoesPossiveis;
    }

    public void setBtnAjudaCombinacoesPossiveis(JButton btnAjudaCombinacoesPossiveis) {
        this.btnAjudaCombinacoesPossiveis = btnAjudaCombinacoesPossiveis;
    }

    public JButton getBtnGerarCombinacoesPossiveis() {
        return btnGerarCombinacoesPossiveis;
    }

    public void setBtnGerarCombinacoesPossiveis(JButton btnGerarCombinacoesPossiveis) {
        this.btnGerarCombinacoesPossiveis = btnGerarCombinacoesPossiveis;
    }

    public JTextField getTxt4Numeros10CombinacoesPossiveis() {
        return txt4Numeros10CombinacoesPossiveis;
    }

    public void setTxt4Numeros10CombinacoesPossiveis(JTextField txt4Numeros10CombinacoesPossiveis) {
        this.txt4Numeros10CombinacoesPossiveis = txt4Numeros10CombinacoesPossiveis;
    }

    public JTextField getTxt4Numeros11CombinacoesPossiveis() {
        return txt4Numeros11CombinacoesPossiveis;
    }

    public void setTxt4Numeros11CombinacoesPossiveis(JTextField txt4Numeros11CombinacoesPossiveis) {
        this.txt4Numeros11CombinacoesPossiveis = txt4Numeros11CombinacoesPossiveis;
    }

    public JTextField getTxt4Numeros12CombinacoesPossiveis() {
        return txt4Numeros12CombinacoesPossiveis;
    }

    public void setTxt4Numeros12CombinacoesPossiveis(JTextField txt4Numeros12CombinacoesPossiveis) {
        this.txt4Numeros12CombinacoesPossiveis = txt4Numeros12CombinacoesPossiveis;
    }

    public JTextField getTxt4Numeros13CombinacoesPossiveis() {
        return txt4Numeros13CombinacoesPossiveis;
    }

    public void setTxt4Numeros13CombinacoesPossiveis(JTextField txt4Numeros13CombinacoesPossiveis) {
        this.txt4Numeros13CombinacoesPossiveis = txt4Numeros13CombinacoesPossiveis;
    }

    public JTextField getTxt4Numeros15CombinacoesPossiveis() {
        return txt4Numeros15CombinacoesPossiveis;
    }

    public void setTxt4Numeros15CombinacoesPossiveis(JTextField txt4Numeros15CombinacoesPossiveis) {
        this.txt4Numeros15CombinacoesPossiveis = txt4Numeros15CombinacoesPossiveis;
    }

    public JTextField getTxt4Numeros1CombinacoesPossiveis() {
        return txt4Numeros1CombinacoesPossiveis;
    }

    public void setTxt4Numeros1CombinacoesPossiveis(JTextField txt4Numeros1CombinacoesPossiveis) {
        this.txt4Numeros1CombinacoesPossiveis = txt4Numeros1CombinacoesPossiveis;
    }

    public JTextField getTxt4Numeros2CombinacoesPossiveis() {
        return txt4Numeros2CombinacoesPossiveis;
    }

    public void setTxt4Numeros2CombinacoesPossiveis(JTextField txt4Numeros2CombinacoesPossiveis) {
        this.txt4Numeros2CombinacoesPossiveis = txt4Numeros2CombinacoesPossiveis;
    }

    public JTextField getTxt4Numeros3CombinacoesPossiveis() {
        return txt4Numeros3CombinacoesPossiveis;
    }

    public void setTxt4Numeros3CombinacoesPossiveis(JTextField txt4Numeros3CombinacoesPossiveis) {
        this.txt4Numeros3CombinacoesPossiveis = txt4Numeros3CombinacoesPossiveis;
    }

    public JTextField getTxt4Numeros4CombinacoesPossiveis() {
        return txt4Numeros4CombinacoesPossiveis;
    }

    public void setTxt4Numeros4CombinacoesPossiveis(JTextField txt4Numeros4CombinacoesPossiveis) {
        this.txt4Numeros4CombinacoesPossiveis = txt4Numeros4CombinacoesPossiveis;
    }

    public JTextField getTxt4Numeros5CombinacoesPossiveis() {
        return txt4Numeros5CombinacoesPossiveis;
    }

    public void setTxt4Numeros5CombinacoesPossiveis(JTextField txt4Numeros5CombinacoesPossiveis) {
        this.txt4Numeros5CombinacoesPossiveis = txt4Numeros5CombinacoesPossiveis;
    }

    public JTextField getTxt4Numeros6CombinacoesPossiveis() {
        return txt4Numeros6CombinacoesPossiveis;
    }

    public void setTxt4Numeros6CombinacoesPossiveis(JTextField txt4Numeros6CombinacoesPossiveis) {
        this.txt4Numeros6CombinacoesPossiveis = txt4Numeros6CombinacoesPossiveis;
    }

    public JTextField getTxt4Numeros7CombinacoesPossiveis() {
        return txt4Numeros7CombinacoesPossiveis;
    }

    public void setTxt4Numeros7CombinacoesPossiveis(JTextField txt4Numeros7CombinacoesPossiveis) {
        this.txt4Numeros7CombinacoesPossiveis = txt4Numeros7CombinacoesPossiveis;
    }

    public JTextField getTxt4Numeros8CombinacoesPossiveis() {
        return txt4Numeros8CombinacoesPossiveis;
    }

    public void setTxt4Numeros8CombinacoesPossiveis(JTextField txt4Numeros8CombinacoesPossiveis) {
        this.txt4Numeros8CombinacoesPossiveis = txt4Numeros8CombinacoesPossiveis;
    }

    public JTextField getTxt4Numeros9CombinacoesPossiveis() {
        return txt4Numeros9CombinacoesPossiveis;
    }

    public void setTxt4Numeros9CombinacoesPossiveis(JTextField txt4Numeros9CombinacoesPossiveis) {
        this.txt4Numeros9CombinacoesPossiveis = txt4Numeros9CombinacoesPossiveis;
    }

    public JTextField getTxt5Numeros1CombinacoesPossiveis() {
        return txt5Numeros1CombinacoesPossiveis;
    }

    public void setTxt5Numeros1CombinacoesPossiveis(JTextField txt5Numeros1CombinacoesPossiveis) {
        this.txt5Numeros1CombinacoesPossiveis = txt5Numeros1CombinacoesPossiveis;
    }

    public JTextField getTxt5Numeros2CombinacoesPossiveis() {
        return txt5Numeros2CombinacoesPossiveis;
    }

    public void setTxt5Numeros2CombinacoesPossiveis(JTextField txt5Numeros2CombinacoesPossiveis) {
        this.txt5Numeros2CombinacoesPossiveis = txt5Numeros2CombinacoesPossiveis;
    }

    public JTextField getTxt5Numeros3CombinacoesPossiveis() {
        return txt5Numeros3CombinacoesPossiveis;
    }

    public void setTxt5Numeros3CombinacoesPossiveis(JTextField txt5Numeros3CombinacoesPossiveis) {
        this.txt5Numeros3CombinacoesPossiveis = txt5Numeros3CombinacoesPossiveis;
    }

    public JTextField getTxt5Numeros4CombinacoesPossiveis() {
        return txt5Numeros4CombinacoesPossiveis;
    }

    public void setTxt5Numeros4CombinacoesPossiveis(JTextField txt5Numeros4CombinacoesPossiveis) {
        this.txt5Numeros4CombinacoesPossiveis = txt5Numeros4CombinacoesPossiveis;
    }

    public JTextField getTxt5Numeros5CombinacoesPossiveis() {
        return txt5Numeros5CombinacoesPossiveis;
    }

    public void setTxt5Numeros5CombinacoesPossiveis(JTextField txt5Numeros5CombinacoesPossiveis) {
        this.txt5Numeros5CombinacoesPossiveis = txt5Numeros5CombinacoesPossiveis;
    }

    public JTextField getTxt5Numeros6CombinacoesPossiveis() {
        return txt5Numeros6CombinacoesPossiveis;
    }

    public void setTxt5Numeros6CombinacoesPossiveis(JTextField txt5Numeros6CombinacoesPossiveis) {
        this.txt5Numeros6CombinacoesPossiveis = txt5Numeros6CombinacoesPossiveis;
    }

    public JTextField getTxtNum1CombinacoesPossiveis() {
        return txtNum1CombinacoesPossiveis;
    }

    public void setTxtNum1CombinacoesPossiveis(JTextField txtNum1CombinacoesPossiveis) {
        this.txtNum1CombinacoesPossiveis = txtNum1CombinacoesPossiveis;
    }

    public JTextField getTxtNum2CombinacoesPossiveis() {
        return txtNum2CombinacoesPossiveis;
    }

    public void setTxtNum2CombinacoesPossiveis(JTextField txtNum2CombinacoesPossiveis) {
        this.txtNum2CombinacoesPossiveis = txtNum2CombinacoesPossiveis;
    }

    public JTextField getTxtNum3CombinacoesPossiveis() {
        return txtNum3CombinacoesPossiveis;
    }

    public void setTxtNum3CombinacoesPossiveis(JTextField txtNum3CombinacoesPossiveis) {
        this.txtNum3CombinacoesPossiveis = txtNum3CombinacoesPossiveis;
    }

    public JTextField getTxtNum4CombinacoesPossiveis() {
        return txtNum4CombinacoesPossiveis;
    }

    public void setTxtNum4CombinacoesPossiveis(JTextField txtNum4CombinacoesPossiveis) {
        this.txtNum4CombinacoesPossiveis = txtNum4CombinacoesPossiveis;
    }

    public JTextField getTxtNum5CombinacoesPossiveis() {
        return txtNum5CombinacoesPossiveis;
    }

    public void setTxtNum5CombinacoesPossiveis(JTextField txtNum5CombinacoesPossiveis) {
        this.txtNum5CombinacoesPossiveis = txtNum5CombinacoesPossiveis;
    }

    public JTextField getTxtNum6CombinacoesPossiveis() {
        return txtNum6CombinacoesPossiveis;
    }

    public void setTxtNum6CombinacoesPossiveis(JTextField txtNum6CombinacoesPossiveis) {
        this.txtNum6CombinacoesPossiveis = txtNum6CombinacoesPossiveis;
    }

    public JTextField getTxt4Numeros14CombinacoesPossiveis() {
        return txt4Numeros14CombinacoesPossiveis;
    }

    public void setTxt4Numeros14CombinacoesPossiveis(JTextField txt4Numeros14CombinacoesPossiveis) {
        this.txt4Numeros14CombinacoesPossiveis = txt4Numeros14CombinacoesPossiveis;
    }

    public JLabel getLblTempoExecução() {
        return lblTempoExecução;
    }

    public void setLblTempoExecução(JLabel lvlTempoExecução) {
        this.lblTempoExecução = lvlTempoExecução;
    }

    public JLabel getLblNomeDesenvolvedor() {
        return lblNomeDesenvolvedor;
    }

    public void setLblNomeDesenvolvedor(JLabel lblNomeDesenvolvedor) {
        this.lblNomeDesenvolvedor = lblNomeDesenvolvedor;
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage((getClass().getResource("/icone/ícone.png"))));
    }
    
    private void centralizarTela(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
}