DROP SCHEMA IF EXISTS `mega-sena`;

CREATE SCHEMA `mega-sena`;

USE `mega-sena`;

CREATE TABLE IF NOT EXISTS `mega-sena`.`aposta_jogo` (
  `id_jogo`         INT     NOT NULL AUTO_INCREMENT COMMENT 'Coluna responsável por identificar unicamente cada aposta registrada no banco de dados.',
  `num_concurso`    INT     NOT NULL                COMMENT 'Coluna responsável por identificar o concurso a qual se refere a aposta efetuada no sistema.',
  `num1`            CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num2`            CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num3`            CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num4`            CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num5`            CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num6`            CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num7`            CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num8`            CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num9`            CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num10`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num11`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num12`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num13`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num14`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num15`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num16`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num17`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num18`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num19`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num20`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num21`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num22`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num23`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num24`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num25`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num26`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num27`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num28`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num29`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num30`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num31`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num32`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num33`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num34`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num35`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num36`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num37`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num38`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num39`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num40`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num41`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num42`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num43`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num44`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num45`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num46`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num47`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num48`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num49`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num50`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num51`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num52`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num53`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num54`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num55`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num56`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num57`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num58`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num59`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `num60`           CHAR(1) NOT NULL DEFAULT 'N'    COMMENT 'Coluna que identificará com S ou N se o jogador apostou no número que dá nome à coluna.',
  `numeros_jogados` INT     NOT NULL                COMMENT 'Coluna responsável por identificar quantos números foram escolhidos nessa aposta, permitido intervalo de 6 à 15.',
  PRIMARY KEY (`id_jogo`));
  
COMMIT;